Algoritmo "Thiago Exe8"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2022
Var
c1, c2, ct, x : real


Inicio
Escreval("OBS: Valores em metros!")
c1 <- 3
c2 <- 6
ct <- (c1 ^ 2) + (c2 ^ 2)
x <- raizq(ct)
escreval("Resposta, o valor de x = ", x)
Fimalgoritmo