Algoritmo "Thiago ex9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thiago
// Data atual  : 08/04/2022
Var
a, b, c : real

Inicio
escreval("Informe o primeiro cateto = ")
leia(a)
escreval("informe o segundo cateto = ")
leia(b)

c := raizq((a ^ 2)+(b ^ 2))

Escreval("a hipotenusa = ", c)

Fimalgoritmo
