Algoritmo "Thiago 9 - AULA 2 23-04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Mostra previsão de remdimento
// Autor(a)    : Thiago
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
deposito, rendimento: real
pergunta

Inicio
escreval("informe o valor do depósito: ")
leia(deposito)
rendimento <- deposito + (deposito * 60)/100
escreval("O valor apos um mês será de: ", rendimento)




Fimalgoritmo