Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2022
Var
   a: inteiro


Inicio
   escreval("Escolha um numero: ")
   leia(a)

   se a > 10 então
      escreval("Esse número é maior que 10")
   senão
      escreval("Esse numero é menor que 10")
   fimse


Fimalgoritmo