Algoritmo "Thiago 8 AULA 2 - 29-03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : CONVERTE REAL PRA DOLAR
// Autor(a)    :THIAGO
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
RS, USD: real

Inicio
Escreval("Conversor de RS --> USD. Digite um valor: ")
Leia(RS)

USD <- RS * 4.70


Escreval("O novo valor é: ", USD   )
Fimalgoritmo