Algoritmo "Thiago 10 AULA 2 28-04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Parcela
// Autor(a)    : Thiago
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
c: real
p: real

Inicio
Escreva("digite o valor do valor que deseja parcelar em 5 vezes: ")
leia(c)
p <- c/5.0
escreval("o valor da das parcelas são: ", p)


Fimalgoritmo