Algoritmo "Thiago 7 - Aula 2 23-03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2022
Var
C, F: real

Inicio

escreval("Conversor de Temperatura °C  --> °F. Digite um valor: ")
leia(C)
F <- (9*C+160) / 5
escreval("Em °F é igual à = ", F,"°C")

Fimalgoritmo