Algoritmo "Thiago 6 - AulA 2 29-03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : TROCA VARIAVEIS
// Autor(a)    : THIAGO
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 

a, b: inteiro
troca: inteiro

Inicio
escreval("Digite o valor a: ")
leia(a)
escreval("Digite o valor b: ")
leia(b)
escreval("Os novos valores são:")
escreval("Digite o valor a: ", b)
escreval("Digite o valor b: ", a)




Fimalgoritmo