Algoritmo "Soma entre dois números (Ex1)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Soma dois números
// Autor(a)    : Thiago
// Data atual  : 29/03/2022
Var
   n1, n2: Inteiro
   soma: inteiro

Inicio
   Escreval("Escolha dois números:")
   Escreval("Primeiro número")
   Leia(n1)
   Escreval("Segundo número")
   Leia(n2)
   soma <- n1 + n2
   Escreval("A soma entre os números ", n1, " e", n2, " é igual à:", soma )

Fimalgoritmo